removing duplicate code; found syntaxcheck is needed (draw before configure, check all nodes are complete

diff --git a/etc__rc.d/ezng b/etc__rc.d/ezng
--- a/etc__rc.d/ezng
+++ b/etc__rc.d/ezng
@@ -23,8 +23,7 @@ load_rc_config $name
 : ${ezng_enable:="NO"}
 : ${ezng_kldload:="netgraph ng_tee ng_etf ng_bpf ng_eiface ng_ether ng_socket ng_ksocket ng_bridge"}
 : ${ezng_config:="/usr/local/etc/ezng.conf"}
-#: ${ezng_rc_source:="/usr/local/share/eznetgraph/ezng.subr"} 
-: ${ezng_rc_source:="/usr/home/pepe/ezng/share__eznetgraph/ezng.subr"}
+: ${ezng_rc_source:="/usr/local/share/eznetgraph/ezng.subr"} 
 : ${ezng_count:="5"}
 : ${ezng_debug:="NO"}
 
@@ -49,42 +48,13 @@ ezng_source_rc_subr() {
   fi
 }
   
-ezng_test_avail() {
-  ezng_source_rc_subr
-  [ $? = 1 ] && { echo "Could not source ezng.subr, exiting ..."; exit 1; }
-  
-  local _type 
-  local _avail_types
-  local _module_path=$(${SYSCTL} -b kern.module_path)
-
-  ${TYPES}
-  [ $? != 0 ] && { 
-    ezdbg "Netgraph support neither found in kernel nor as loaded modules, trying to load module now."; 
-    ${KLDLOAD} ${_module_path}/netgraph.ko;
-    [ $? != 0 ] && { echo "Could not load ${_module_path}/netgraph.ko, please assure netgraph support is available in kernel or as module before continuing. Exiting ... "; exit 1; }
-    ezdbg " ... netgraph.ko loaded successfully."; 
-  }
-
-  _avail_types=$( ${TYPES} | ${GREP} -v "total\|Number\|------" | ${SED} 's/^[ \t]*//' | ${CUT} -d ' ' -f 1 )
-  for _type in ${EZNG_SUPPORTED}; do 
-    ezdbg "Checking whether needed type $_type is supported by kernel or module... "
-    # Check is done with a substring match:
-    [ "$_type" != "${_avail_types%$_type*}" ] && {
-      ezdbg "     ... $_type not found. Trying to load as module ... " ;
-      ${KLDLOAD} ${_module_path}/$_type.ko ;
-      [ $? != 0 ] && { echo "Could not load ${_module_path}/$_type.ko, please assure this module is available or loaded or in kernel before continuing. Exiting ... "; exit 1; } ;
-    }
-  done
-  # if we are here, all needed types are either available via kernel or loaded as module
-}
-
 ezng_start() {
   ezng_source_rc_subr
   [ $? = 1 ] && return 1
 
   # check all moDules are loaded (and load them if needed)
   ezng_test_avail
-  [ $? = 1 ] && { ${ECHO} "ERROR, missing netgraph type(s). Exiting ... "; return 1 }
+  [ $? = 1 ] && { ${ECHO} "ERROR, missing netgraph type(s). Exiting ... "; return 1; }
 
   # load netgraph if there is no active netgraph 
 
